
export const ACTIVITY_CATEGORIES = Object.freeze({
  AUTHENTICATION: 'AUTHENTICATION',
  SESSION: 'SESSION',
  PROFILE: 'PROFILE',
  CONNECTED_ACCOUNT: 'CONNECTED_ACCOUNT',
  SECURITY: 'SECURITY',
  PRIVACY: 'PRIVACY',
});

export const ALLOWED_ACTIVITY_CATEGORIES = Object.freeze(Object.values(ACTIVITY_CATEGORIES));

export const ACTIVITY_ACTIONS = Object.freeze({
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',
  PHONE_CHANGED: 'PHONE_CHANGED',
  ACCOUNT_CONNECTED: 'ACCOUNT_CONNECTED',
  ACCOUNT_DISCONNECTED: 'ACCOUNT_DISCONNECTED',
  PRIVACY_UPDATED: 'PRIVACY_UPDATED',
  SESSION_REVOKED: 'SESSION_REVOKED',
});
