export const ACTIVITY_ACTIONS = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  EMAIL_CHANGED: 'EMAIL_CHANGED',
  PHONE_CHANGED: 'PHONE_CHANGED',
  ACCOUNT_CONNECTED: 'ACCOUNT_CONNECTED',
  ACCOUNT_DISCONNECTED: 'ACCOUNT_DISCONNECTED',
  PRIVACY_UPDATED: 'PRIVACY_UPDATED',
  TWO_FACTOR_ENABLED: 'TWO_FACTOR_ENABLED',
  TWO_FACTOR_DISABLED: 'TWO_FACTOR_DISABLED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  ALL_SESSIONS_REVOKED: 'ALL_SESSIONS_REVOKED'
};

export const ACTIVITY_CATEGORIES = {
  AUTHENTICATION: 'AUTHENTICATION',
  PROFILE: 'PROFILE',
  CONNECTED_ACCOUNT: 'CONNECTED_ACCOUNT',
  SECURITY: 'SECURITY',
  PRIVACY: 'PRIVACY',
  SESSION: 'SESSION'
};
